### ISSUE TITLE
Robomaster S1 SDK explainations

### ISSUE THREAD

**Issue by goatgitt** [brunoga/robomaster#3]
Hi Bruno,
I didn't understand how did you modify the robomaster SDK for enable it for robomaster S1
Could you explain how did you do that? 
I am a newbie in hacking and I don't understand what I have to change.

**Comment by brunoga** [comment]
https://www.bug-br.org.br/s1_sdk_hack.zip

**Comment by CoyoteProd** [comment]
There is a minimal or maximal firmware version to apply the Hack ?

Thanks for the work....

**Comment by brunoga** [comment]
No idea if there is a minimum version but I would guess not. It also works
on the latest version.

**Comment by sam-cms** [comment]
Hello Bruno, thanks for sharing. I saw that the link that you provided does not work anymore ( https://www.bug-br.org.br/s1_sdk_hack.zip ). 
Is there another way I can get this zip ?  
Thanks

**Comment by brunoga** [comment]
It should be up again now.

**Comment by sam-cms** [comment]
Great ! Thanks for sharing ! A lot of computer vision developing in on the way !
