### ISSUE TITLE
After pushing files, no more wifi connection on S1 with latest firmware v 00.06.0500

### ISSUE THREAD

**Issue by CoyoteProd** [brunoga/robomaster#4]
Having adb shell is ok.

But pushing files with the upload.sh command seems to break something, because it's unable to connect via wifi now (sid is visible, but unable to connect)...

The robot make only one shime sound at boot (doc mention 2 chimes)

**Comment by brunoga** [comment]
I assume you are talking about the S1 SDK Hack. If so, are you by any chance using Windows and manually reproduced the steps in upload.sh to upload files to the robot? If so, there is most likelly one other thing you should have done:

adb shell chmod 755 /data/dji_hdvt_uav

After rebooting, it should work.

That being said, you were supposed to hear 2 chimes even without doing the above so I suspect you are still missing something else but I have no way to know what unless you shows me everything you did.

**Comment by CoyoteProd** [comment]
Yes, you are right, I made modifications from a Windows plateform.
Brilliant.. it's working... !!! and now I hear 2 shimes and I can connect via Wifi normally...
Thanks a lot for your help !

**Comment by brunoga** [comment]
Glad it is working.
