### ISSUE TITLE
python api in robomaster sdk 

### ISSUE THREAD

**Issue by cuthate** [brunoga/robomaster#6]
How can I edit and use python api in windows (.py)?
E.g
pidPitch = rm_ctrl.PIDCtrl()
pidYaw = rm_ctrl.PIDCtrl()

**Comment by cuthate** [comment]
I am using EP
I also have a look at the documentation

e.g.
I can't execute in sdk  ->  variable_b = robot_ctrl.get_battery_percentage()

**Comment by brunoga** [comment]
The code you showed is for the internal robot API, not the external SDK. It will not work with the external SDK. Documentation for the external SDK is [here ](https://robomaster-dev.readthedocs.io/zh_CN/latest/).

Note this repository has no relationship to the Python SDK whatsoever.

**Comment by cuthate** [comment]
ok... i got it...
I want to use the functions of the api and implement it in the sdk...
because i want to use raspberry pi control

Or is there a way to call programs in dji from sdk?
