### ISSUE TITLE
TCP connecting fail

### ISSUE THREAD

**Issue by SherwinDengxiong** [brunoga/robomaster#7]
I want to connect the RoboMaster s1 using the following code, but failed during TCP connecting.

import socket
import sys

host='192.168.2.1'
port=40923

def main():
    address=(host,int(port))
    s=socket.socket(socket.AF_INET,socket.SOCK_STREAM)

    print("-----------------connecting-------------")
    s.connect(address)
    print("connected!")

    while True:
        msg=input(">>> input sdk command")
        if msg.upper()=="Q":
            break

        s.send(msg.encode("utf-8"))

        try: 
            buf=s.recv(1024)
            print(buf.decode("utf-8"))
        except socket.error as e:
            print("ERROR receiving :",e)
            sys.exit(1)
        if not len(buf):
            break

    s.shutdown(socket.SHUT_WR)
    s.close()

if __name__ == '__main__':
    main()

Do I need to hack the hardware?

**Comment by brunoga** [comment]
Not sure why you are posting it here but, yes. The S1 dose not support the external SDK so you need to hack it to be able to do that.
